VERSION: 2
INPUT:
  MASK_FORMAT: "bitmask"
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  BACKBONE:
    FREEZE_AT: 0
    NAME: "build_effnet_fpn_backbone"
  FPN:
    IN_FEATURES: ["s2", "s3", "s5", "s6"]
  RPN:
    IN_FEATURES: ["p2", "p3", "p4", "p5"]
    PRE_NMS_TOPK_TRAIN: 12000
    POST_NMS_TOPK_TRAIN: 1000    
  PROPOSAL_GENERATOR:
    NAME: "RPN"    
  RETINANET:
    NUM_CLASSES: &num_classes 20
    IOU_THRESHOLDS: [0.4, 0.5]
    IOU_LABELS: [0, -1, 1]
    SMOOTH_L1_LOSS_BETA: 0.0
  ROI_HEADS:
    IN_FEATURES: ["p2", "p3", "p4", "p5"]
    NUM_CLASSES: *num_classes
    NAME: "StandardROIHeads"
  ROI_BOX_HEAD:
    NAME: "FastRCNNConvFCHead"
    NUM_FC: 2
    NUM_CONV: 1
    NORM: ""
    POOLER_RESOLUTION: 7
  ROI_MASK_HEAD:
    CLS_AGNOSTIC_MASK: false
    CONV_DIM: 256
    NAME: "MaskRCNNConvUpsampleHead"
    NORM: ""
    NUM_CONV: 0
    POOLER_RESOLUTION: 14
    POOLER_TYPE: ROIAlignV2
  SEM_SEG_HEAD:
    NUM_CLASSES: *num_classes
  MASK_ON: False
  LOAD_PROPOSALS: False    
  WEIGHTS: ""    
SOLVER:
  IMS_PER_BATCH: 12
  BASE_LR: 0.0005
  STEPS: (60000, 800000)
  MAX_ITER: 100000
  WARMUP_ITERS: 0
  CHECKPOINT_PERIOD: 5000
DATALOADER:
  NUM_WORKERS: 8
DATASETS:
  TRAIN: ("coco_2017_train_20", )  
  TEST: ("coco_2017_val_20", )
  # TRAIN: ("penn_fudan", )
  # TEST: ("penn_fudan_test",)
